### ISSUE TITLE
REQ-204 회원가입

### ISSUE THREAD

**Issue by LSH9084** [greenlotte4/team2-lotteon-project#23]
회원가입 기능을 구현한다.
- 아이디 중복 체크 구현
- 닉네임 중복 체크 구현
- 이메일 인증 구현
- 유효성 검사 구현
- 회원가입 구현
- 회원가입시 포인트 추가 및 커스터머 포인트 업데이트

**Comment by minhi0449** [comment]
2024.10.21 회원가입 : 일반 회원가입 시 member, customer 데이터 DB 분리하여 저장 완료
